### ISSUE TITLE
Kurbo support

### ISSUE THREAD

**Issue by bitec0de** [notgull/piet-hardware#8]
Are you intending to support Kurbo?

Drawing curved lines is essential for what I was hoping to do with Piet, at least circular arcs, I'd be fine without full Béziers.

**Comment by notgull** [comment]
`kurbo` is already supported by `piet` and this crate. Curved lines are tessellated into triangles by the internal algorithm. You should just be able to use [`stroke`](https://docs.rs/piet-hardware/latest/piet_hardware/struct.RenderContext.html#method.stroke) to draw it.

Is there anything specific from `kurbo` that this crate doesn't support yet?

**Comment by bitec0de** [comment]
Oh, forgive me, I searched the docs for "kurbo" but didn't see it mentioned.. I  generated the docs with `cargo doc --no-deps`, perhaps that's why.
